spring.application.name=Tickets App.

spring.datasource.url=jdbc:h2:mem:tickets_db
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.datasource.username=sanyi
spring.datasource.password=${DB_PASSWORD:12345}
spring.jpa.defer-datasource-initialization=true

spring.thymeleaf.enabled=true